### DISCUSSION TITLE
How to solve the problem "The msg_id is too low, the client time has to be synchronized."

### DISCUSSION THREAD

**Discussion by weiwuwei** [tangyoha/telegram_media_downloader#101] [Q&A] [answered]
The error showed up when running the command ```python3 media_downloader.py```

**Comment by tangyoha** [comment]
pip3 install -r requirements.txt

**Reply by weiwuwei** [reply]
Tried, but still showed the same error message

**Reply by tangyoha** [reply, marked as answer]
update telegram_media_downloader first

**Comment by tangyoha** [comment]
Hello! The error "The msg_id is too low, the client time has to be synchronized" is caused by incorrect system time.

**Solution**:

**1. Synchronize your system time**:

```bash
# On Linux/macOS
sudo ntpdate -u time.nist.gov
# or
sudo timedatectl set-ntp true

# On Windows
w32tm /resync
```

**2. Check your system time**:

```bash
date
```

Make sure it matches the current time. Telegram requires accurate time synchronization.

**3. If using Docker**:

Add timezone configuration to docker-compose.yaml:

```yaml
services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Sync with host time
      - /etc/timezone:/etc/timezone:ro
```

**4. If using a VPS or VM**:

Ensure NTP service is running:

```bash
sudo systemctl enable systemd-timesyncd
sudo systemctl start systemd-timesyncd
```

**Why this happens**:
- Telegram uses time-based message IDs for security
- If your system time is off by more than a few seconds, authentication fails
- This is especially common in VMs, containers, or systems without NTP

After syncing time, restart the program and it should work.
