### DISCUSSION TITLE
是否支持下载群里的link

### DISCUSSION THREAD

**Discussion by xinmans** [tangyoha/telegram_media_downloader#129] [Q&A]
比如电报群里经常会发一些http://xxx 的link，希望匹配一些关键字的link获取这些link，可以二次做一些开发，比如做一些邮件提醒

**Comment by tangyoha** [comment]
你好！关于提取群组中的 HTTP 链接并进行二次开发的需求，这是一个很有趣的想法。

**当前实现方式**：

目前程序主要专注于下载媒体文件，不直接提取文本链接。但可以通过以下方式实现：

**方案1：使用 download_filter 配合自定义脚本**

1. 配置下载所有消息的文本
2. 修改源码或使用 Pyrogram 编写脚本提取链接

**方案2：功能建议**

建议作者可以添加类似的配置：
```yaml
link_extraction:
  enable: true
  keywords:
    - "关键词1"
    - "关键词2"
  output_file: links.txt
  notification:
    email: your@email.com
    webhook: https://your-webhook-url
```

**方案3：使用 Webhook 集成**

可以配合现有的 Web GUI，添加 webhook 功能，当检测到匹配的链接时发送通知。

这是一个很实用的功能扩展，建议提交 Feature Request！
