### DISCUSSION TITLE
Account change issue账号更改问题

### DISCUSSION THREAD

**Discussion by mhdy2233** [tangyoha/telegram_media_downloader#136] [Q&A] [answered]
我想问下我要换账号或者换成bot_api要怎么做才能进行更换
I would like to ask what I need to do if I want to change my account or switch to bot_api.

**Comment by tangyoha** [comment, marked as answer]
停止-> 删除session文件夹 -＞ 重新运行

**Comment by tangyoha** [comment]
你好！关于更换账号或切换到 bot_api 的方法：

Hello! Here is how to change accounts or switch to bot_api:

**Method 1: Change to a different user account / 更换用户账号**

1. Stop the program / 停止程序
2. Delete session files / 删除 session 文件:
```bash
rm -rf ./sessions/*
```
3. Update config.yaml with new credentials / 更新配置:
```yaml
api_hash: new_api_hash
api_id: new_api_id
# Remove bot_token if exists
```
4. Restart and login with new phone number / 重启并用新手机号登录

**Method 2: Switch to bot mode / 切换到机器人模式**

1. Stop the program / 停止程序
2. Delete session files / 删除 session 文件:
```bash
rm -rf ./sessions/*
```
3. Update config.yaml / 更新配置:
```yaml
api_hash: your_api_hash
api_id: your_api_id
bot_token: "your_bot_token"  # Add this line
# Remove or comment out chat list
allowed_user_ids:
  - your_user_id
```
4. Restart the program / 重启程序

**Method 3: Keep both configurations / 保留两个配置**

Create separate directories for different accounts:
```bash
# User account
./user_account/
  config.yaml
  sessions/
  
# Bot account
./bot_account/
  config.yaml
  sessions/
```

**Important / 重要提示**:
- Always backup your data.yaml before switching / 切换前备份 data.yaml
- Session files are account-specific / Session 文件是账号专用的
- You cannot use both user and bot mode simultaneously in one instance / 不能同时使用用户和机器人模式
