### DISCUSSION TITLE
Program automatically stops程序自动停止

### DISCUSSION THREAD

**Discussion by mhdy2233** [tangyoha/telegram_media_downloader#138] [Q&A]
The program will automatically stop after running for a period of time, and the files will not be uploaded completely. When it is started again, the task will continue but the files left over from the last time will not be uploaded.
程序运行一段时间后就会自动停止，并且文件并没有上传完全，再次启动会继续任务但是并不会上传上次遗留下来的文件。

**Comment by tangyoha** [comment]
Hello! The program stopping automatically and not uploading remaining files is likely related to upload configuration or error handling.

你好！程序自动停止且未上传完所有文件，通常与上传配置或错误处理有关。

**Common Causes / 常见原因**:

1. **Upload timeout / 上传超时**
2. **Network connection issues / 网络连接问题**
3. **Rclone configuration problems / Rclone 配置问题**
4. **Memory or resource limits / 内存或资源限制**

**Solutions / 解决方案**:

**1. Check upload configuration / 检查上传配置**:
```yaml
upload_drive:
  enable_upload_file: true
  remote_dir: drive:/path
  upload_adapter: rclone
  rclone_path: /usr/bin/rclone
  before_upload_file_zip: false
  after_upload_file_delete: false  # Set to false to keep files if upload fails
```

**2. Add restart policy in docker-compose.yaml**:
```yaml
services:
  telegram_media_downloader:
    restart: unless-stopped  # Auto-restart on crash
```

**3. Check logs for errors / 检查日志**:
```bash
# Check log files
cat log/*.log | grep ERROR
```

**4. Manual upload of remaining files / 手动上传遗留文件**:
```bash
# Use rclone to upload remaining files
rclone copy /path/to/downloads remote:/path
```

**5. Increase resource limits / 增加资源限制**:
```yaml
services:
  telegram_media_downloader:
    mem_limit: 2g
    cpus: 2
```

Check the log files for specific error messages to identify the exact cause.
