### DISCUSSION TITLE
Regarding wsl deployment docker pull image, after the file is successfully downloaded, the file disappears.

### DISCUSSION THREAD

**Discussion by yjxzx** [tangyoha/telegram_media_downloader#147] [Q&A]
question :The docker image program file was downloaded successfully. For example, the .flac.temp file becomes .flac. After that, the file disappears. It's not in the recycle bin, and it's not there when searching for "everything". ID and hash have been scrambled.
## docker-compose.yaml

```yaml
version: "3.3"

services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/c/dd:/app/temp"
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"  

##  config.yaml
yaml
Copy code
api_hash: 52c67330ec5cc89
api_id: 2121
bot_token: 6305891x7nBdDv0f1_U
chat:
  - chat_id: -1001784767214
    last_read_message_id: 0

media_types:
  - audio
  - voice
  - photo
file_formats:
  audio:
    - all
  voice:
    - all
  photo:
    - all
save_path: /mnt/c/dd
language: EN
file_path_prefix:
  - chat_title
  - media_datetime

**Comment by tangyoha** [comment]
Hello! The issue with files disappearing after download in WSL is likely related to the volume mapping configuration.

**Problem Analysis**:

Your configuration has a conflict:
```yaml
volumes:
  - "/mnt/c/dd:/app/temp"  # Mapped to temp directory
save_path: /mnt/c/dd        # But save_path points to host path
```

**The Issue**:
1. Files are downloaded to `/app/temp` inside the container
2. After completion, they are moved to `save_path: /mnt/c/dd`
3. But `/mnt/c/dd` is not accessible from inside the container (its the host path)
4. The move operation fails silently, causing files to disappear

**Solution**:

Fix your docker-compose.yaml:

```yaml
version: "3.3"

services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/c/dd:/app/downloads"  # Map to downloads, not temp
      - "./temp:/app/temp"           # Separate temp directory
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"
```

And update config.yaml:

```yaml
api_hash: your_api_hash
api_id: your_api_id
bot_token: your_bot_token
chat:
  - chat_id: -1001784767214
    last_read_message_id: 0

media_types:
  - audio
  - voice
  - photo
file_formats:
  audio:
    - all
  voice:
    - all
  photo:
    - all
save_path: /app/downloads  # Use container path, not host path
language: EN
file_path_prefix:
  - chat_title
  - media_datetime
```

**Key Points**:
- `save_path` should use the container path (`/app/downloads`), not the host path
- The volume mapping connects container path to host path
- Temp files should be in a separate directory

After making these changes, restart the container and files should save correctly to `/mnt/c/dd` on your Windows system.
