### DISCUSSION TITLE
406 erro

### DISCUSSION THREAD

**Discussion by A1q2yang** [tangyoha/telegram_media_downloader#198] [Q&A]
输入手机号后弹Telegram says: [406 Not Acceptable] - [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")

**Comment by tangyoha** [comment]
你好！错误 `406 UPDATE_APP_TO_LOGIN` 表示你使用的 Telegram API 版本过旧，需要更新。

**解决方案**：

1. **更新到最新版本**：
```bash
# 如果使用 Docker
docker pull tangyoha/telegram_media_downloader:latest

# 如果使用 Python
pip install --upgrade pyrogram
```

2. **检查 Pyrogram 版本**：
确保使用的是兼容的 Pyrogram 版本。项目要求特定版本的 Pyrogram。

3. **重新生成 API 凭证**：
有时候旧的 API 凭证会导致这个问题：
- 访问 https://my.telegram.org
- 删除旧的应用
- 创建新的应用获取新的 api_id 和 api_hash

4. **删除旧的 session 文件**：
```bash
rm -rf ./sessions/*
```

5. **使用最新的 Docker 镜像**：
```yaml
services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    # 不要使用固定版本号
```

**如果问题持续**：

这可能是 Telegram 服务器端的限制。可以尝试：
- 等待几小时后重试
- 使用不同的网络环境
- 确认你的 Telegram 账号没有被限制

通常更新到最新版本就能解决这个问题。
