### DISCUSSION TITLE
转发时 标题内容 关键词替换

### DISCUSSION THREAD

**Discussion by AguaC1** [tangyoha/telegram_media_downloader#201] [Ideas]
转发时 标题内容 关键词替换 比如在转发的时候里边有 广告 可以设置关键词匹配 把广告去除

**Comment by hk112019** [comment]
同样需要

**Comment by tangyoha** [comment]
你好！关于转发时替换标题内容中的关键词，这个功能目前需要通过配置来实现。

**当前的实现方式**：

可以使用 `download_filter` 来过滤掉包含特定关键词的消息：

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: "caption and 广告 not in caption"  # 排除包含"广告"的消息
```

**更复杂的过滤**：

```yaml
download_filter: "not caption or (广告 not in caption and 推广 not in caption)"
```

**关于内容替换功能**：

目前程序主要专注于下载，不支持直接修改 caption 内容。如果需要这个功能，可以考虑：

1. **下载后处理**：
   - 先下载文件
   - 使用脚本读取并修改文件的元数据

2. **功能建议**：
可以建议作者添加类似的配置：
```yaml
caption_replace:
  - pattern: "广告"
    replacement: ""
  - pattern: "推广.*"
    replacement: ""  # 支持正则表达式
```

3. **使用外部工具**：
   - 下载后使用 Python 脚本批量处理
   - 使用 exiftool 等工具修改文件元数据

这是一个很实用的功能建议，可以考虑提交 Feature Request 让作者评估是否加入到项目中。
