### DISCUSSION TITLE
远程服务器配置了clash代理，跑docker版的启动报连接超时

### DISCUSSION THREAD

**Discussion by Konfucius-D** [tangyoha/telegram_media_downloader#202] [Q&A]
有大佬可以告诉我怎么配置么

**Comment by tangyoha** [comment]
你好！关于在远程服务器上使用 Clash 代理的配置问题，这里提供几种解决方案：

**方案1：在 config.yaml 中配置代理**

```yaml
api_hash: your_api_hash
api_id: your_api_id
proxy:
  scheme: http  # 或 socks5，取决于 Clash 的配置
  hostname: 127.0.0.1  # 如果 Clash 在同一台机器
  port: 7890  # Clash 的 HTTP 代理端口
```

**方案2：使用 Docker 网络配置**

如果 Clash 运行在宿主机上，需要使用宿主机 IP：

```yaml
proxy:
  scheme: http
  hostname: 172.17.0.1  # Docker 默认网关，指向宿主机
  port: 7890
```

**方案3：使用环境变量（在 docker-compose.yaml 中）**

```yaml
services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    environment:
      - http_proxy=http://172.17.0.1:7890
      - https_proxy=http://172.17.0.1:7890
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./downloads:/app/downloads
```

**检查 Clash 配置**：

1. 确认 Clash 允许局域网连接：
```yaml
# Clash config.yaml
allow-lan: true
bind-address: "*"
```

2. 检查防火墙是否允许 Docker 容器访问代理端口

**测试代理连接**：

```bash
# 进入容器测试
docker exec -it telegram_media_downloader sh
curl --proxy http://172.17.0.1:7890 https://api.telegram.org
```

如果还有问题，可以提供具体的错误日志。
