### DISCUSSION TITLE
Downloaded only selected media

### DISCUSSION THREAD

**Discussion by akchaudhary6532** [tangyoha/telegram_media_downloader#210] [Q&A]
I want to download around 400 media from total of 2000+ media.
I added the message ids that I wanted to download in `data.yaml` under `ids_to_retry` but it doesn't work because all ids are repopulated again which I do not want.

How can a achieve this?

**Comment by tangyoha** [comment]
Hello! To download only selected media (specific message IDs), you can use the `download_filter` feature instead of `ids_to_retry`.

**Solution: Use download_filter with message IDs**

In your `config.yaml`, configure like this:

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0  # Start from beginning
    download_filter: "id in [123, 456, 789, ...]"  # Your 400 message IDs
```

**For a large list of IDs**, you can use a range or multiple conditions:

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: "id in [101, 102, 103, 104, 105, 201, 202, 203, ...]"
```

**Alternative: Use a Python list in the filter**

If you have many IDs, you can create a more manageable configuration:

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: "id >= 100 and id <= 500 and id not in [110, 120, 130, ...]"
```

**Why ids_to_retry doesnt work**:
- `ids_to_retry` is designed for automatic retry of failed downloads
- It gets repopulated by the system when downloads fail
- Its not meant for manual selection of specific messages

**Best practice**:
1. Create a list of your 400 message IDs
2. Use `download_filter` with the `in` operator
3. Set `last_read_message_id: 0` to scan from the beginning
4. The program will only download messages matching your filter

This way, youll download exactly the 400 media files you want without downloading all 2000+.
