### DISCUSSION TITLE
只能下载jpg图片

### DISCUSSION THREAD

**Discussion by xzlibin** [tangyoha/telegram_media_downloader#241] [Q&A]
只能下载图片jpg 其他文件下载失败
.2025-04-21 11:25:16.444 | SUCCESS  | main:main:667 - Successfully started (Press Ctrl+C to stop)
2025-04-21 11:30:39.283 | ERROR    | main:download_media:428 - Message[22]: 无法下载,因为以下异常:
['NoneType' object is not subscriptable].
2025-04-21 11:31:36.333 | ERROR    | main:download_media:428 - Message[24]: 无法下载,因为以下异常:
['NoneType' object is not subscriptable].
2025-04-21 11:35:10.637 | ERROR    | main:download_media:428 - Message[30]: 无法下载,因为以下异常:
['NoneType' object is not subscriptable].
2025-04-21 11:37:38.514 | ERROR    | main:download_media:428 - Message[32]: 无法下载,因为以下异常:
['NoneType' object is not subscriptable].
2025-04-21 11:38:43.015 | ERROR    | main:download_media:428 - Message[34]: 无法下载,因为以下异常:     这是日志
![photo_2025-04-24_10-29-07](https://github.com/user-attachments/assets/59312a05-3a75-4419-a8d3-12052df5c948)

![photo_2025-04-24_10-29-14](https://github.com/user-attachments/assets/74b8a6a9-9a36-4770-b5aa-f75ee1d981aa)

希望大佬解答

**Comment by tangyoha** [comment]
你好！根据错误信息 `NoneType object is not subscriptable`，这通常是因为某些媒体类型的元数据缺失导致的。

**问题原因**：
- 某些消息的媒体对象为空或缺少必要的属性
- 可能是特殊类型的消息（如投票、位置分享等）
- 或者是已删除/过期的媒体

**解决方案**：

1. **检查配置的媒体类型**：
```yaml
media_types:
  - photo      # 图片
  - video      # 视频
  - document   # 文档
  - audio      # 音频
  # 不要包含 voice, video_note 等如果不需要
```

2. **使用过滤器排除问题消息**：
```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: "media and media.file_size and media.file_size > 0"
```

3. **检查文件格式配置**：
```yaml
file_formats:
  document:
    - pdf
    - zip
    - rar
  video:
    - mp4
    - mkv
  # 使用 all 可能会包含不支持的格式
```

4. **查看详细错误日志**：
在 `log/` 目录下查看完整的错误堆栈，可以帮助定位具体是哪个字段为 None。

**临时解决方案**：

如果某些消息持续失败，可以跳过它们：
```yaml
download_filter: "id not in [22, 24, 30, 32, 34]"  # 跳过失败的消息ID
```

建议先尝试添加 `download_filter` 来过滤掉有问题的消息，如果问题持续，可以提供完整的错误日志以便进一步诊断。
