### ISSUE TITLE
[Feature]: 請問能否增加按話題進行分別的功能。

### ISSUE THREAD

**Issue by tsinit2001** [tangyoha/telegram_media_downloader#236]
### Description

在一些羣組中，允許可以存在許多話題。能否增加一個針對這些話題的篩選功能。

### Suggested Solution

1、按照話題來劃分是否下載，只下載一個羣組中的幾個話題下的文件，或者下載羣組中指定話題之外的其他所有話題中的文件。
2、按照話題來分別保存下載的文件到對應的目錄中。

**Comment by tangyoha** [comment]
你好！关于按话题（topic）进行分别下载的功能，目前已经有部分支持：

**当前可用的功能**：
1. 使用 `download_filter` 按 topic_id 筛选：
```yaml
chat:
  - chat_id: -100xxxxxxxxxx
    last_read_message_id: 0
    download_filter: topic_id == 10  # 只下载话题 ID 为 10 的内容
```

2. 排除特定话题：
```yaml
chat:
  - chat_id: -100xxxxxxxxxx
    last_read_message_id: 0
    download_filter: topic_id != 10  # 下载除话题 10 之外的所有内容
```

3. 下载多个指定话题：
```yaml
chat:
  - chat_id: -100xxxxxxxxxx
    last_read_message_id: 0
    download_filter: topic_id in [10, 20, 30]
```

**关于自动按话题名称分类保存**：
目前 PR #274 正在开发这个功能，可以自动获取话题名称并创建对应的文件夹。期待这个功能能尽快合并到主分支！

在此之前，可以手动为不同话题创建多个 chat 配置项，使用不同的 `file_path_prefix` 来分别保存。
