### ISSUE TITLE
[Bug]: pyrogram.session.auth.Auth报错

### ISSUE THREAD

**Issue by xinmans** [tangyoha/telegram_media_downloader#238]
### telegram_media_downloader version or commit

the newest

### What happened?

sudo docker-compose run --rm telegram_media_downloader
报错

docker-compose.yaml

```

services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    container_name: telegram_media_downloader_stock
    restart: always
    #build: .
    ports:
      # Here is what you need to edit
      - "25007:5000"
    #environment:
    #  - http_proxy=http://192.168.101.30:10811
    #  - https_proxy=http://192.168.101.30:10811
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      # Here is what you need to edit
      - "/trunenas_pool/telegram_newrecord/:/app/downloads/"



      # The following is what you don't need to edit
      - "./config.yaml:/app/config.yaml"
      - "./data.yaml:/app/data.yaml"
      - "./log/:/app/log/"
      - "./sessions/:/app/sessions"
      - "./temp/:/app/temp"
# volumes:
#   sessions:
#   temp:

```

### Expected Behavior

希望能到输入手机号码部分

### Current Behavior

2025-04-04 09:32:40.004 | ERROR    | __main__:main:682 - 0
Traceback (most recent call last):

  File "/app/media_downloader.py", line 704, in <module>
    main()
    └ <function main at 0x7ff2047f7f60>

> File "/app/media_downloader.py", line 666, in main
    app.loop.run_until_complete(start_server(client))
    │   │    │                  │            └ <module.pyrogram_extension.HookClient object at 0x7ff20483c390>
    │   │    │                  └ <function start_server at 0x7ff2047f7e20>
    │   │    └ <function BaseEventLoop.run_until_complete at 0x7ff2080427a0>
    │   └ <_UnixSelectorEventLoop running=False closed=False debug=False>
    └ <module.app.Application object at 0x7ff204802890>

  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           │      └ <method 'result' of '_asyncio.Task' objects>
           └ <Task finished name='Task-1' coro=<start_server() done, defined at /app/media_downloader.py:635> exception=KeyError(0)>

  File "/app/media_downloader.py", line 639, in start_server
    await client.start()
          │      └ <function HookClient.start at 0x7ff205145ee0>
          └ <module.pyrogram_extension.HookClient object at 0x7ff20483c390>

  File "/app/module/pyrogram_extension.py", line 1256, in start
    is_authorized = await self.connect()
                          │    └ <function HookClient.connect at 0x7ff205145e40>
                          └ <module.pyrogram_extension.HookClient object at 0x7ff20483c390>

  File "/app/module/pyrogram_extension.py", line 1233, in connect
    await self.load_session()
          │    └ <function Client.load_session at 0x7ff205ceca40>
          └ <module.pyrogram_extension.HookClient object at 0x7ff20483c390>

  File "/usr/local/lib/python3.11/site-packages/pyrogram/client.py", line 720, in load_session
    await Auth(
          └ <class 'pyrogram.session.auth.Auth'>
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/auth.py", line 289, in create
    raise e
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/auth.py", line 104, in create
    res_pq = await self.invoke(raw.functions.ReqPqMulti(nonce=nonce))
                   │    │      │   │         │                └ 4362076678721524790862140264393302364
                   │    │      │   │         └ <class 'pyrogram.raw.functions.req_pq_multi.ReqPqMulti'>
                   │    │      │   └ <module 'pyrogram.raw.functions' from '/usr/local/lib/python3.11/site-packages/pyrogram/raw/functions/__init__.py'>
                   │    │      └ <module 'pyrogram.raw' from '/usr/local/lib/python3.11/site-packages/pyrogram/raw/__init__.py'>
                   │    └ <function Auth.invoke at 0x7ff206808400>
                   └ <pyrogram.session.auth.Auth object at 0x7ff204553cd0>
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/auth.py", line 75, in invoke
    return self.unpack(response)
           │    │      └ <_io.BytesIO object at 0x7ff204599580>
           │    └ <staticmethod(<function Auth.unpack at 0x7ff206808360>)>
           └ <pyrogram.session.auth.Auth object at 0x7ff204553cd0>
  File "/usr/local/lib/python3.11/site-packages/pyrogram/session/auth.py", line 68, in unpack
    return TLObject.read(b)
           │        │    └ <_io.BytesIO object at 0x7ff204599580>
           │        └ <classmethod(<function TLObject.read at 0x7ff207bd8ae0>)>
           └ <class 'pyrogram.raw.core.tl_object.TLObject'>
  File "/usr/local/lib/python3.11/site-packages/pyrogram/raw/core/tl_object.py", line 33, in read
    return cast(TLObject, objects[int.from_bytes(b.read(4), "little")]).read(b, *args)
           │    │         │                      │ │                         │   └ ()
           │    │         │                      │ │                         └ <_io.BytesIO object at 0x7ff204599580>
           │    │         │                      │ └ <method 'read' of '_io.BytesIO' objects>
           │    │         │                      └ <_io.BytesIO object at 0x7ff204599580>
           │    │         └ {85337187: <class 'pyrogram.raw.types.res_pq.ResPQ'>, 2211011308: <class 'pyrogram.raw.types.pq_inner_data.PQInnerData'>, 285...
           │    └ <class 'pyrogram.raw.core.tl_object.TLObject'>
           └ <function cast at 0x7ff208080c20>

KeyError: 0

### Relevant log output

```shell

```

**Comment by tangyoha** [comment]
你好！这个 `KeyError: 0` 错误通常与 Telegram API 连接问题有关。

**可能的原因**：
1. **网络连接问题**：无法正常连接到 Telegram 服务器
2. **代理配置问题**：如果使用代理，配置可能不正确
3. **防火墙阻止**：防火墙可能阻止了与 Telegram 的连接
4. **API 服务器问题**：Telegram API 服务器暂时不可用

**解决方案**：

1. **检查网络连接**：
```bash
# 测试是否能访问 Telegram
ping api.telegram.org
```

2. **如果使用代理，取消注释并配置代理**：
```yaml
# 在 config.yaml 中添加
proxy:
  scheme: http  # 或 socks5
  hostname: 192.168.101.30
  port: 10811
```

3. **或者在 docker-compose.yaml 中使用环境变量**：
```yaml
environment:
  - http_proxy=http://192.168.101.30:10811
  - https_proxy=http://192.168.101.30:10811
```

4. **检查 API 凭证**：
   - 确认 `api_id` 和 `api_hash` 是否正确
   - 可以在 https://my.telegram.org 重新获取

5. **尝试删除旧的 session 文件**：
```bash
rm -rf ./sessions/*
```

6. **使用交互模式重新授权**：
```bash
docker compose run --rm telegram_media_downloader
```

建议先检查网络和代理配置，这是最常见的原因。
