### ISSUE TITLE
[Feature]: 能否支持在配置文件config.yaml中使用ipv6代理？

### ISSUE THREAD

**Issue by vorabend** [tangyoha/telegram_media_downloader#239]
### Description

经过测试，proxy-hostname的值使用ipv6地址会报错（尝试过写成ipv6域名和"[26xx:19xx:40xx:295::]"这种格式），均提示无法连接。

### Suggested Solution

经过测试，proxy-hostname的值使用ipv6地址会报错（尝试过写成ipv6域名和"[26xx:19xx:40xx:295::]"这种格式），均提示无法连接。

**Comment by tangyoha** [comment]
你好！关于 IPv6 代理支持的问题，这是一个有效的功能请求。

**临时解决方案**：
1. 使用 IPv6 域名而不是直接使用 IPv6 地址
2. 在本地配置一个支持 IPv6 的代理转发（如使用 nginx 或 socat）

**IPv6 地址格式问题**：
标准的 IPv6 地址格式在 URL 中需要用方括号包裹，例如：
```
[2001:db8::1]
```

但在 YAML 配置中，这可能需要特殊处理。建议开发者在代码中添加对 IPv6 地址的支持，检测地址格式并自动添加方括号。

**建议的配置格式**（需要代码支持）：
```yaml
proxy:
  scheme: socks5
  hostname: "2001:db8::1"  # 或 "[2001:db8::1]"
  port: 7890
```

这需要在代码层面修改 pyrogram 的代理配置部分，以正确处理 IPv6 地址格式。
