### ISSUE TITLE
[Bug]: 飞牛nas里安装总是提示python media_downloader.py not found

### ISSUE THREAD

**Issue by vicentory** [tangyoha/telegram_media_downloader#245]
### telegram_media_downloader version or commit

docker下载的最新版本

### What OS are you seeing the problem on?

Other Linux Distro

### Python Version

python 3.12

### What happened?

飞牛docker里提示如下，请大佬帮忙看一下，多谢。
Windows版本安装好了，是可以用的，但飞牛nas里无法安装成功。
![Image](https://github.com/user-attachments/assets/4d3edab6-c958-4c9b-ad63-7f6076a19f57)

### Expected Behavior

希望能出个飞牛教程，

### Current Behavior

nas里容器创建失败

### Possible Solution

是不是容器内部没有python media_downloader.py

### Relevant log output

```shell

```

**Comment by zy19941113** [comment]
同样问题，不知如何解决

**Comment by ToFuKing** [comment]
出现过同样问题, volumes 一个个映射就好了

**Comment by zy19941113** [comment]
> 出现过同样问题, volumes 一个个映射就好了

请问如何映射文件，飞牛并不支持单独映射文件，仅支持映射文件夹

**Comment by lkll1314** [comment]
> > 出现过同样问题, volumes 一个个映射就好了
> 
> 请问如何映射文件，飞牛并不支持单独映射文件，仅支持映射文件夹

试试直接复制连接到docker的映射，不要去选择

**Comment by tangyoha** [comment]
根据社区反馈，这个问题与 Docker 卷映射配置有关。

**问题原因**：
飞牛 NAS 的 Docker 界面可能不支持某些复杂的卷映射配置，导致容器启动失败。

**解决方案**：

1. **使用 Docker Compose**（推荐）：
创建 `docker-compose.yml` 文件：
```yaml
version: '3'
services:
  telegram_media_downloader:
    image: tangyoha/telegram_media_downloader:latest
    container_name: telegram_media_downloader
    volumes:
      - ./downloads:/app/downloads
      - ./config.yaml:/app/config.yaml
      - ./data.yaml:/app/data.yaml
    restart: unless-stopped
```

2. **手动映射卷**（如 @ToFuKing 建议）：
不要使用飞牛的图形界面批量映射，而是：
- 一个一个手动添加卷映射
- 或者直接复制 Docker 命令，不使用图形界面选择

3. **检查文件路径**：
确保映射的本地路径存在：
```bash
mkdir -p /your/path/downloads
touch /your/path/config.yaml
touch /your/path/data.yaml
```

4. **首次运行**：
使用交互模式进行首次授权：
```bash
docker run -it --rm -v ./config.yaml:/app/config.yaml tangyoha/telegram_media_downloader:latest
```

如果问题仍然存在，建议提供完整的 Docker 启动命令或 docker-compose.yml 配置，这样可以更准确地定位问题。
