### ISSUE TITLE
[Feature]:

### ISSUE THREAD

**Issue by Bainianbai** [tangyoha/telegram_media_downloader#246]
### Description

能否支持下载 用户与机器bot 的聊天内容。

### Suggested Solution

在客户端与机器人聊天内容能导出

### Alternatives

无

### Additional Context

无

**Comment by tangyoha** [comment]
你好！关于下载用户与机器人（bot）的聊天内容，这个功能是支持的。

**配置方法**：

在 config.yaml 中添加机器人的 chat_id：

```yaml
chat:
  - chat_id: bot_username  # 或者使用 bot 的数字 ID
    last_read_message_id: 0
```

**获取 bot 的 chat_id**：

1. **使用用户名**：
```yaml
chat:
  - chat_id: "@bot_username"  # 例如 @download_bot
    last_read_message_id: 0
```

2. **使用数字 ID**：
   - 在 Telegram 中与 bot 聊天
   - 转发一条消息给 @userinfobot
   - 它会告诉你 bot 的数字 ID

3. **使用程序获取**：
```python
# 运行程序后，在日志中可以看到所有对话的 ID
```

**完整配置示例**：

```yaml
api_hash: your_api_hash
api_id: your_api_id
chat:
  - chat_id: "@your_bot_username"
    last_read_message_id: 0
media_types:
  - audio
  - photo
  - video
  - document
save_path: /path/to/downloads
```

这样就可以下载你与机器人之间的所有媒体文件了。如果有其他问题，欢迎继续提问！
