### ISSUE TITLE
[Bug]: 机器人一直下载

### ISSUE THREAD

**Issue by chenleidaye** [tangyoha/telegram_media_downloader#247]
### telegram_media_downloader version or commit

v2.2.5

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

下载视频

### Expected Behavior

不知道

### Current Behavior

![Image](https://github.com/user-attachments/assets/646cc1de-1c25-4ba9-8aac-27fb30c6ad86)我是用docker安装的，容器一个劲的在下载，tg上用机器人停止下载又显示No Task，是变量都不管用吗，我用过滤下载也不会按条件筛选下载，也不会用rclone上传
config.yaml文件如下，隐私部分用*代替

api_hash: *
api_id: *
bot_token: "**"
chat:
  - chat_id: -*
    last_read_message_id: 0
download_filter: caption == r'.*#我的最爱.*' or caption == r'.*#个人喜好.*'
file_formats:
  audio:
    - all
  document:
    - all
  video:
    - all
file_path_prefix:
  - chat_title
  - media_datetime
media_types:
  - audio
  - photo
  - video
  - document
  - voice
  - video_note
 in linux please use /
 save_path: /vol1/1000/downloads/tg
upload_drive:
  enable_upload_file: true
  remote_dir: drive:/115/tg
  upload_adapter: rclone
  rclone_path: /usr/bin/rclone
  before_upload_file_zip: false
  after_upload_file_delete: true
proxy:
  scheme: socks5
  hostname: 172.17.0.1
  port: 7890
language: ZH
allowed_user_ids: **

### Relevant log output

```shell

```

**Comment by tangyoha** [comment]
你好！看起来你的配置有几个问题需要修正：

1. **download_filter 位置错误**：`download_filter` 应该放在每个 chat 配置下，而不是全局配置中。

2. **正则表达式语法问题**：在 YAML 中使用正则表达式需要正确的引号。

修正后的配置：

```yaml
api_hash: *
api_id: *
bot_token: "**"
chat:
  - chat_id: -*
    last_read_message_id: 0
    download_filter: "caption and ('#我的最爱' in caption or '#个人喜好' in caption)"
file_formats:
  audio:
    - all
  document:
    - all
  video:
    - all
file_path_prefix:
  - chat_title
  - media_datetime
media_types:
  - audio
  - photo
  - video
  - document
  - voice
  - video_note
save_path: /vol1/1000/downloads/tg
upload_drive:
  enable_upload_file: true
  remote_dir: drive:/115/tg
  upload_adapter: rclone
  rclone_path: /usr/bin/rclone
  before_upload_file_zip: false
  after_upload_file_delete: true
proxy:
  scheme: socks5
  hostname: 172.17.0.1
  port: 7890
language: ZH
allowed_user_ids: **
```

**关于机器人一直下载的问题**：
- 如果没有设置 `download_filter`，机器人会下载所有消息
- 确保过滤器语法正确，否则会被忽略
- 可以通过 Web GUI (默认端口 5050) 查看当前下载任务状态

修改配置后需要重启容器才能生效。
