### ISSUE TITLE
[Bug]: caption不支持中文

### ISSUE THREAD

**Issue by kingtalk** [tangyoha/telegram_media_downloader#248]
### telegram_media_downloader version or commit

V2.2.5

### What OS are you seeing the problem on?

Other Linux Distro

### What happened?

A bug happened!
config中文件过滤caption使用中文则无法启动，删除即可正常启动。
chat:
- chat_id: 
  last_read_message_id: 0
  #download_filter: caption == '#我的最爱'
则无法启动，注释掉 '#我的最爱'也无法启动，注释掉caption可以正常启动。在chat_id不变的情况下。报错中关键词有"utf-8"

### Expected Behavior

正常启动，且只下载标题中精准匹配"#我的最爱"的关键词。

### Current Behavior

目前，caption中包含中文就无法启动docker容器。还是说中文关键词需要转义？

### Relevant log output

```shell

```

**Comment by tangyoha** [comment]
你好！关于 caption 中文支持的问题，这通常是 YAML 文件编码导致的。

请尝试以下解决方案：

1. 确保 config.yaml 文件使用 UTF-8 编码保存
2. 在 YAML 中使用引号包裹中文内容：

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: 'caption == "#我的最爱"'
```

或者使用单引号：

```yaml
chat:
  - chat_id: your_chat_id
    last_read_message_id: 0
    download_filter: "caption == '#我的最爱'"
```

3. 如果使用 Docker，确保容器的 locale 设置支持中文：

```bash
docker exec -it container_name locale
# 应该看到 UTF-8 相关的输出
```

如果问题仍然存在，可以提供完整的错误日志吗？这样可以更准确地定位问题。
